# Generated by Django 2.2.1 on 2019-05-31 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs', models.FloatField(blank=True, null=True, verbose_name='factor de servicio')),
                ('HP', models.FloatField(blank=True, null=True, verbose_name='potencia de motor')),
                ('Np', models.FloatField(blank=True, null=True, verbose_name='dientes del piñón')),
                ('angle', models.FloatField(blank=True, null=True, verbose_name='ángulo')),
                ('Pd', models.FloatField(blank=True, null=True, verbose_name='paso diametral del engrane')),
                ('Wg', models.FloatField(blank=True, null=True, verbose_name='RPMs del engrane')),
                ('Wp', models.FloatField(blank=True, null=True, verbose_name='RPMs del piñón')),
                ('PotD', models.FloatField(blank=True, null=True, verbose_name='potencia de diseño')),
                ('Ng', models.FloatField(blank=True, null=True, verbose_name='dientes del engrane')),
                ('Dp', models.FloatField(blank=True, null=True, verbose_name='paso diametral del piñón')),
                ('Vt', models.FloatField(blank=True, null=True, verbose_name='velocidad tangencial')),
                ('C', models.FloatField(blank=True, null=True, verbose_name='distancia entre centros')),
                ('Ft', models.FloatField(blank=True, null=True, verbose_name='fuerza transmitida')),
                ('F', models.FloatField(blank=True, null=True, verbose_name='ancho de la cara')),
                ('Av', models.IntegerField(blank=True, null=True, verbose_name='Calidad')),
                ('kv', models.FloatField(blank=True, null=True)),
                ('Cpf', models.FloatField(blank=True, null=True, verbose_name='factor de proporción del piñón')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gear',
                'verbose_name_plural': 'Gears',
            },
        ),
    ]
