# Generated by Django 2.2.1 on 2019-06-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20190531_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='Deg',
            field=models.FloatField(null=True, verbose_name='Diametro exterior del engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Dep',
            field=models.FloatField(null=True, verbose_name='Diametro exterior del piñón'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Dg',
            field=models.FloatField(null=True, verbose_name='paso diametral del engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Drg',
            field=models.FloatField(null=True, verbose_name='Diametro de raíz del engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Drp',
            field=models.FloatField(null=True, verbose_name='Diametro de raíz del piñón'),
        ),
        migrations.AddField(
            model_name='gear',
            name='addendum',
            field=models.FloatField(null=True, verbose_name='Addendum'),
        ),
        migrations.AddField(
            model_name='gear',
            name='clair',
            field=models.FloatField(null=True, verbose_name='Claro'),
        ),
        migrations.AddField(
            model_name='gear',
            name='dedendum',
            field=models.FloatField(null=True, verbose_name='Dedendum'),
        ),
        migrations.AddField(
            model_name='gear',
            name='depth_total',
            field=models.FloatField(null=True, verbose_name='Profunidad total'),
        ),
        migrations.AddField(
            model_name='gear',
            name='t',
            field=models.FloatField(null=True, verbose_name='Espesor de diente'),
        ),
        migrations.AddField(
            model_name='gear',
            name='work_depth',
            field=models.FloatField(null=True, verbose_name='Profunidad de trabajo'),
        ),
    ]
