# Generated by Django 2.2.1 on 2019-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_gear_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='Dbg',
            field=models.FloatField(null=True, verbose_name='Diametro de círculo base del engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Dbp',
            field=models.FloatField(null=True, verbose_name='Diametro de círculo base del piñón'),
        ),
        migrations.AddField(
            model_name='gear',
            name='I',
            field=models.FloatField(null=True, verbose_name='Factor geométrico'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Jg',
            field=models.FloatField(null=True, verbose_name='Factor geométrico del engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Jp',
            field=models.FloatField(null=True, verbose_name='Factor geométrico del piñón'),
        ),
        migrations.AddField(
            model_name='gear',
            name='P',
            field=models.FloatField(null=True, verbose_name='Paso circular'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Ynp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='Znp',
            field=models.FloatField(null=True),
        ),
    ]
