# Generated by Django 2.2.1 on 2019-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20190603_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='Cma',
            field=models.FloatField(null=True, verbose_name='Factor de alineación'),
        ),
        migrations.AddField(
            model_name='gear',
            name='km',
            field=models.FloatField(null=True, verbose_name='Factor de distribución de carga'),
        ),
    ]
