# Generated by Django 2.2.1 on 2019-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20190603_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='Satg',
            field=models.FloatField(null=True, verbose_name='Esfuerzo de flexión ajustado en el engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Satp',
            field=models.FloatField(null=True, verbose_name='Esfuerzo de flexión ajustado en el piñón'),
        ),
    ]
