# Generated by Django 2.2.1 on 2019-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_auto_20190603_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='Sacg',
            field=models.FloatField(null=True, verbose_name='Esfuerzo de contacto ajustado en el engrane'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Sacp',
            field=models.FloatField(null=True, verbose_name='Esfuerzo de contacto ajustado en el piñón'),
        ),
        migrations.AddField(
            model_name='gear',
            name='Sc',
            field=models.FloatField(null=True, verbose_name='Esfuerzo de contacto'),
        ),
    ]
