# Generated by Django 2.2.1 on 2019-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20190603_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='RV',
            field=models.FloatField(null=True, verbose_name='Relación de Velocidad'),
        ),
    ]
